### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by cuihairu** [jdf2e/nutui-icons#26]
react-dom.development.js:86  Warning: u4: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at u4 (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/@nutui_icons-react-taro.js?v=fcc1ffda:925:80)
    at div
    at div
    at Badge (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/chunk-WNW3JXQ6.js?v=fcc1ffda:1318:15)
    at div
    at TabbarItem (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/chunk-WNW3JXQ6.js?v=fcc1ffda:1380:44)
    at div
    at div
    at Tabbar (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/@nutui_nutui-react-taro_dist_esm_Tabbar.js?v=fcc1ffda:54:41)
    at Footer (http://localhost:10086/components/footer/footer.tsx:30:19)
    at taro-view-core
    at ReactComponent (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/@tarojs_components.js?v=fcc1ffda:314:7)
    at TaroViewCore
    at Index
    at div
    at PageWrapper (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/chunk-KLMDKYIW.js?v=fcc1ffda:233:9)
    at App (http://localhost:10086/app.ts:8:3)
    at AppWrapper (http://localhost:10086/@fs/Users/cui/Workspaces/salon-app/node_modules/.vite/deps/chunk-KLMDKYIW.js?v=fcc1ffda:301:7)

fix #23

**Comment by xiaoyatong** [comment]
fixed，1.0.5
